baseURL = 'https://dzikri.my.id/'
languageCode = 'en-us'
title = 'Home'
copyright = "© 2024 Dzikri "
theme = 'PaperMod'
#ShowToc = true

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks= true
  ShowCodeCopyButtons= true

[params.profileMode]
  enabled = true
  title = 'Dzikri Hakim'
  subtitle = 'This blog is my space to share knowledge dan experinces.'
  imageUrl = "https://i.ibb.co.com/wQbxpFR/picofme-1.png"
  imageTitle = "<title of image as alt>"
  imageWidth = 197
  imageHeight = 198

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "/posts"

    [[params.profileMode.buttons]]
    name = "Series"
    url = "/series"


[[params.socialicons]]
name = "linkedin"
url = "https://linkedin.com"

[[params.socialicons]]
name = "youtube"
url = "https://youtube.com/"

[[params.socialicons]]
name = "github"
url = "https://github.com/"

[[params.socialicons]]
name = "instagram"
url = "https://instagram.com/"







# ------------------------------

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10



# --------------------------------------

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# ---------------------------------------

[outputs]
home = [ "HTML", "RSS", "JSON" ]
